---
- name: Ensure project folder exists
  file:
    path: /srv/build2teach
    state: directory
    owner: admin 
    group: docker
    mode: '0755'

- name: Clone project repository
  git:
    repo: 'https://github.com/lien-nguyen/DWCraft.git'
    dest: /srv/build2teach/app
    version: main
    force: yes

- name: Create Traefik config folder
  file:
    path: /srv/build2teach/traefik
    state: directory
    owner: admin 
    group: docker
    mode: '0755'

- name: Render Traefik config
  template:
    src: traefik.yml.j2
    dest: /srv/build2teach/traefik/traefik.yml
    owner: admin 
    group: docker
    mode: '0644'

- name: Create acme.json with proper permissions
  copy:
    content: ''
    dest: /srv/build2teach/traefik/acme.json
    owner: admin 
    group: docker
    mode: '0600'

- name: Render docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /srv/build2teach/docker-compose.yml
    owner: admin 
    group: docker
    mode: '0644'

- name: Pull and deploy services with Docker Compose
  become: true
  become_user: admin 
  shell: |
    cd /srv/build2teach
    docker compose pull || true
    docker compose up -d --build
  args:
    executable: /bin/bash
