---
- name: Ensure project folder exists
  file:
    path: /srv/build2teach
    state: directory
    owner: admin
    group: docker
    mode: '0755'

- name: Clone or update DWCraft repository (for build2teach app)
  become_user: admin
  git:
    repo: git@github.com:lien-nguyen/DWCraft.git
    dest: /srv/build2teach
    version: main
    update: yes
    force: yes

- name: Pull latest Docker image from GitHub Container Registry
  become_user: admin
  shell: |
    docker pull ghcr.io/lien-nguyen/build2teach:latest

- name: Stop and remove old container (if exists)
  become_user: admin
  shell: |
    docker rm -f build2teach || true

- name: Run new Docker container
  become_user: admin
  shell: |
    docker run -d --name build2teach \
      --env-file /srv/build2teach/.env \
      -p 8000:8000 \
      ghcr.io/lien-nguyen/build2teach:latest

- name: Copy operational scripts to dev-tools folder 
  copy: 
    src: ../../../../ops-scripts/ # Todo-Check if this path is correct
    dest: /srv/build2teach/dev-tools/
    owner: admin
    group: docker
    mode: '0755'
