---
- name: Bootstrap Build2Teach Test Server
  hosts: build2teach-dev 
  become: true

  vars:
    deploy_user: admin
    project_folder: /srv/build2teach

  tasks:
    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Ensure deploy user exists
      user:
        name: "{{ deploy_user }}"
        groups: docker
        append: yes
        shell: /bin/bash
        create_home: yes

    - name: Create project directory
      file:
        path: "{{ project_folder }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: docker
        mode: '0755'
