services:
  django-db:
    image: postgres:15
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "55433:5432"

  django-app:
    build: 
      context: ..
      dockerfile: build2teach/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/build2teach
    ports:
      - "8000:8000"
    depends_on:
      - django-db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=dwh_course.settings

volumes:
  pgdata: